services:
  server:
    build:
      context: packages/server
      args:
      - NODE_ENV=production
    image: wangzilong8/cdigi-web_server
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4096M
    environment:
      - NODE_ENV=production
      - orm_host=db
      - orm_port=3306
      - orm_username=root
      - orm_password=mnbvch
      - orm_database=cdigi_database
      - redis_host=redis
      - redis_port=6379
    restart: always
    ports:
      - 8002:30000
    secrets:
      - db-password
    volumes:
      # - ./server:/code
      - server-data:/code
    # volumes:
    #   - ./server/src:/code/src:ro
    #   - ./server/package.json:/code/package.json
    #   - ./server/package-lock.json:/code/package-lock.json
    #   - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
      - redis
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=cdigi_database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  redis:
    image: redis:alpine
    restart: always
    networks:
      - private
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  client:
    build:
      context: packages/client
    image: wangzilong8/cdigi-web_client
      # target: development
    ports:
      - 8001:80
    restart: always
    networks:
      - public
    # depends_on:
    #   - server
networks:
  public:
  private:
volumes:
  # back-notused:
  server-data:
  db-data:
  redis-data:
secrets:
  db-password:
    file: scripts/password.txt